server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/classes?UseSSL=false&useUnicode=yes&characterEncoding=UTF-8&characterSetResults=UTF-8&serverTimezone=UTC&zeroDateTimeBehavior=convertToNULL&allowPublicKeyRetrieval=true
    username: root
    password: root
  data:
    jpa:
      repositories:
        bootstrap_mode: default
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        dialect, storage_engine: innodb
    generate-ddl: true
    show-sql: true
jwt:
  secret: secret_token